// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSp5RbLBZKMLHT0RJH3Zk5JRXZ4LOrQYc', // Usando la clave API del plist
    appId: '1:933474056744:ios:eb4afc196bdafda3f8131d', // Usando el GOOGLE_APP_ID del plist
    messagingSenderId: '933474056744',
    projectId: 'manitoxpress-cf855',
    databaseURL: 'https://manitoxpress-cf855-default-rtdb.firebaseio.com',
    storageBucket: 'manitoxpress-cf855.appspot.com',
    androidClientId: '933474056744-5m32u4i8ltf1r975qbghcfe7slh6fmop.apps.googleusercontent.com',
    iosClientId: '933474056744-6o1u1238gkoj9q7052b2i8je0r1m4ij4.apps.googleusercontent.com', // Usando el CLIENT_ID del plist
    iosBundleId: 'com.xpress.manitosxpress', // Bundle ID ajustado
  );
}
